---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gosec
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unparam
    - unused
    - gocyclo
    - goconst
    - nakedret

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
